spring.datasource.url=jdbc:postgresql://dpg-d75ummnkijhs73c6pjn0-a:5432/lipputietokanta
spring.datasource.username=projekti
spring.datasource.password=oikea_salasana

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update