spring.datasource.url=jdbc:postgresql://dpg-d75ummnkijhs73c6pjn0-a:5432/lipputietokanta
spring.datasource.username=projekti
spring.datasource.password=RENDERIN_POSTGRES_SALASANA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true